import fs from "node:fs";
import { pathToFileURL } from "node:url";
import { VOCAB_TS_PATH } from "./project.mjs";

// vocabulary.ts has no TS syntax inside the array literal itself (only the
// interfaces use TS syntax), so under tsx this import just works and gives
// us real parsed objects instead of a fragile regex parse of the whole file.
export async function readVocabulary() {
  const mod = await import(pathToFileURL(VOCAB_TS_PATH).href + `?t=${Date.now()}`);
  return { vocabulary: mod.VOCABULARY, categories: mod.VOCAB_CATEGORIES };
}

// Each vocab entry is authored as a single line, e.g.:
//   { hiragana: "たべる", romaji: "taberu", meaning: "comer", ..., category: "verbos" },
// hiragana alone isn't a unique key (e.g. "はな" = both "flor" and "nariz"),
// so entries are located by matching hiragana + category on the same line.
export function findEntryLine(fileText, hiragana, category) {
  const lines = fileText.split("\n");
  const hiraganaNeedle = `hiragana: "${hiragana}"`;
  const categoryNeedle = `category: "${category}"`;
  const index = lines.findIndex((line) => line.includes(hiraganaNeedle) && line.includes(categoryNeedle));
  if (index === -1) {
    throw new Error(`Could not find vocabulary.ts entry for hiragana="${hiragana}" category="${category}"`);
  }
  return { lines, index };
}

// Marks a single entry as generated by rewriting its line in place.
// Idempotent: re-running with a new imagePath replaces the old one instead
// of appending a duplicate field.
export function markGenerated(fileText, hiragana, category, imagePath) {
  const { lines, index } = findEntryLine(fileText, hiragana, category);
  let line = lines[index];

  // Strip any previous generated/imagePath fields from an earlier run.
  line = line.replace(/,\s*generated:\s*(true|false)/, "");
  line = line.replace(/,\s*imagePath:\s*"[^"]*"/, "");

  const insertion = `, generated: true, imagePath: "${imagePath}"`;
  const closingBraceIndex = line.lastIndexOf("}");
  if (closingBraceIndex === -1) {
    throw new Error(`Unexpected line shape, no closing brace: ${line}`);
  }
  line = line.slice(0, closingBraceIndex) + insertion + " " + line.slice(closingBraceIndex);

  lines[index] = line;
  return lines.join("\n");
}

export function readVocabTsText() {
  return fs.readFileSync(VOCAB_TS_PATH, "utf8");
}

export function writeVocabTsText(text) {
  fs.writeFileSync(VOCAB_TS_PATH, text, "utf8");
}
